//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DctPad.rc
//
#define IDS_REGISTRY_SUBKEY             11
#define IDS_INTERM_TT_SAVEAS            12
#define IDS_APPNAME                     19
#define IDS_TRANSFERTEXT                31
#define IDS_FATALERROR                  35
#define IDS_MUSTHAVEDICT                36
#define IDS_DICTATINGTO                 44
#define IDS_INTERM_TT_OPEN              54
#define IDS_INTERM_TT_SAVE              55
#define IDS_INTERM_TT_CUT               56
#define IDS_INTERM_TT_COPY              57
#define IDS_INTERM_TT_PASTE             58
#define IDS_INTERM_TT_LISTEN            59
#define IDS_INTERM_TT_SENDTEXTNOW       60
#define IDS_INTERM_TT_PLAYAUDIO         61
#define IDS_INTERM_TT_SENDTEXTAUTO      62
#define IDS_INTERM_TT_CUTALL            69
#define IDS_DCTPADLISTENING             70
#define IDS_DCTPADNOTLISTENING          71
#define IDS_INTERM_TT_CORRECTION        72
#define IDS_INTERM_ASKSAVE              73
#define IDS_EXCEPTION_FATAL             75
#define IDS_INTERM_TT_ADDWORD           96
#define IDS_E_LOADSTRING                97
#define IDS_E_INITAPPLICATION           98
#define IDS_E_REGCREATEKEY              99
#define IDS_E_COINITIALIZE              100
#define IDR_DICT_ACCELTABLE             101
#define IDI_APP                         101
#define IDS_E_LOADVCMD                  101
#define IDD_ABOUT                       101
#define IDI_DOCICON                     102
#define IDS_E_OUTOFMEM                  102
#define IDR_COMMANDS                    102
#define IDI_DICTOFF                     103
#define IDS_E_ALREADYRUNNING            103
#define IDI_DICTON                      104
#define IDS_E_LOADRICHED32DLL           105
#define IDI_DICTCMDON                   105
#define IDI_CMDON                       106
#define IDS_E_VCMDQUIT                  107
#define IDR_ACCELERATOR1                108
#define IDS_E_VCMDCOCREATE              126
#define IDS_E_VCMDQUERY                 127
#define IDS_E_VCMDREGISTER              128
#define IDS_E_VCMDACTIVATE              133
#define IDS_BADDIR                      137
#define IDS_E_NOSOUNDCARD               139
#define IDS_E_VCMDCOGETCLASS            159
#define IDS_E_VCMDCREATEINSTANCE        160
#define IDS_DICTFILEEXT                 168
#define IDS_NOTDICTFILE                 169
#define IDS_SAVECURFILE                 170
#define IDS_ERRORWRITINGFILE            171
#define IDS_ERRORREADINGFILE            172
#define IDS_UNSAVEDFILE                 173
#define IDS_DICTFILES                   174
#define IDS_MSRESEARCH                  175
#define IDS_MSHOME                      176
#define IDS_MSDICTINSTALL               177
#define IDS_INSTALLDIR                  178
#define IDR_INTERM_LONGMENU             180
#define IDB_INTERM_TOOLBAR              191
#define IDC_BEGINSCAN                   1000
#define IDC_PRODUCTVERSION              1000
#define IDC_CANCEL                      1005
#define IDC_VIEW                        1006
#define IDC_SEND                        1013
#define IDM_INTERM_HELPTOPICS           40001
#define IDM_INTERM_WEB_RESEARCH         40002
#define IDM_INTERM_WEB_HOME             40003
#define IDM_INTERM_HELPABOUT            40004
#define IDM_INTERM_WHATCANISAY          40005
#define ID_BUTTON40006                  40006
#define ID_BUTTON40007                  40007
#define ID_BUTTON40008                  40008
#define ID_BUTTON40009                  40009
#define ID_BUTTON40010                  40010
#define ID_BUTTON40011                  40011
#define ID_BUTTON40012                  40012
#define ID_BUTTON40013                  40013
#define IDM_HELPCONTENTS                40014
#define ID_BUTTON40014                  40014
#define ID_BUTTON40015                  40015
#define ID_BUTTON40016                  40016
#define IDM_ABOUT                       40017
#define ID_BUTTON40017                  40017
#define ID_BUTTON40018                  40018
#define ID_BUTTON40019                  40019
#define ID_BUTTON40020                  40020
#define ID_BUTTON40021                  40021
#define IDM_MSDICT_CORRECT              40026
#define IDM_INTERM_FILEOPEN             40054
#define IDM_INTERM_FILESAVEAS           40055
#define IDM_INTERM_EDITCUT              40057
#define IDM_INTERM_EDITCOPY             40058
#define IDM_INTERM_EDITPASTE            40059
#define IDM_INTERM_EDITDELETE           40060
#define IDM_INTERM_EDITSELECTALL        40061
#define IDM_INTERM_DICTLISTEN           40062
#define IDM_INTERM_DICTNOTLISTEN        40063
#define IDM_INTERM_SHOWALWAYSTOP        40067
#define IDM_INTERM_SHOWSETFONT          40070
#define IDM_INTERN_SELECTENTIREWORD     40076
#define IDM_INTERM_EDITCUTALL           40078
#define ID_FILE_SENDTEXTTO_THECLIPBOARD 40079
#define IDM_INTERM_FILESAVE             40085
#define IDM_INTERM_FILENEW              40086
#define IDM_INTERM_EXIT                 40087
#define IDS_INTERM_TT_NEW               40087
#define IDM_ADDWORD                     40088
#define IDS_TEXTFILES                   40088
#define IDM_INTERM_CAPITALIZE           40089
#define IDS_TEXTFILEEXT                 40089
#define IDS_PROMPTTEXT                  40090
#define IDS_E_VCMDSITEINFOSET           40091
#define IDS_INTERM_TT_CAPITALIZE        40116
#define IDS_SHUTDOWN                    40129
#define IDS_SAVENEWFILE                 40131
#define IDS_INVALIDFILETYPE             40132
#define IDM_INTERM_EDITUNDO             65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40022
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
