//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Srtest.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SRTEST_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_DLGFINDMODE                 129
#define IDD_TABISRCENTRAL               132
#define IDD_TABISRATTRIB                133
#define IDD_TABISRGRAMMAR               134
#define IDD_DIALOGENGSELECT             135
#define IDD_TABISRGRAMCFG               137
#define IDD_TABISRGRAMDICT              138
#define IDD_TABISRNOTIFY                141
#define IDD_ISRGRAMNOTIFY               142
#define IDD_TABISRDIALOGS               143
#define IDD_DLGGRAMPATH                 145
#define IDD_TABISRRESAUDIO              149
#define IDD_TABISRRESBASIC              150
#define IDD_TABISRRESCORR               151
#define IDD_TABISRRESGRAPH              153
#define IDD_TABISRRESMEM                154
#define IDD_TABISRRESMERGE              155
#define IDD_TABISRRESMODGUI             156
#define IDD_TABISRRESSpeaker            157
#define IDD_TABISRRESEVAL               160
#define IDD_GRAMCUSTOMADD               161
#define IDD_TABISRRESSCORES             163
#define IDC_ENUMMODES                   1000
#define IDC_EDITMAIN                    1002
#define IDC_GRAMNOTIFYOUTPUT            1004
#define IDC_FINDCRITERIA                1007
#define IDC_EDITMODENAME                1010
#define IDC_EDITMFG                     1011
#define IDC_EDITLANG                    1012
#define IDC_MODENAME                    1013
#define IDC_LISTGRAMSTAT                1016
#define IDC_LISTENUMMODES               1017
#define IDC_LISTGRAMMARS                1018
#define IDC_CENTGRAMLOAD                1024
#define IDC_CENTGRAMRELEASEALL          1025
#define IDC_STATICPROP                  1032
#define IDC_CENTPAUSE                   1033
#define IDC_CENTRESUME                  1034
#define IDC_ATTRGAIN                    1034
#define IDC_ATTRTHRESH                  1035
#define IDC_ATTRENERGY                  1036
#define IDC_ATTRIBECHO                  1037
#define IDC_ATTRMIC                     1038
#define IDC_ATTRCPU                     1039
#define IDC_ATTRSPEAKER                 1040
#define IDC_ATTRTIMEOUT                 1041
#define IDC_GRAMCTL                     1041
#define IDC_ATTRTIMEOUTC                1041
#define IDC_GRAMTRAIN                   1042
#define IDC_ATTRTIMEOUTI                1042
#define IDC_GRAMTRAINPHRASE             1043
#define IDC_GRAMTRAINQUERY              1044
#define IDC_GRAMMARTRAIN                1045
#define IDC_ENUMOUTPUT1A                1046
#define IDC_ENUMOUTPUT3A                1047
#define IDC_ENUMOUTPUT2A                1048
#define IDC_ENUMOUTPUT4A                1049
#define IDC_ENUMOUTPUT5A                1050
#define IDC_ENUMOUTPUT6A                1051
#define IDC_MODEADD                     1052
#define IDC_ENUMOUTPUT7A                1052
#define IDC_LISTENUMMODES1              1053
#define IDC_ENUMOUTPUT8A                1054
#define IDC_GRAMARCHIVE                 1055
#define IDC_ENUMOUTPUT9A                1055
#define IDC_GRAMCFGLIST                 1056
#define IDC_ENUMOUTPUT10A               1056
#define IDC_GRAMCFGLISTGET              1057
#define IDC_ENUMOUTPUT11A               1057
#define IDC_GRAMCFGLISTREMOVE           1058
#define IDC_ENUMOUTPUT12A               1058
#define IDC_GRAMCFGLISTAPPEND           1059
#define IDC_ENUMOUTPUT13A               1059
#define IDC_GRAMCFGLISTGET4             1060
#define IDC_GRAMCFGLISTSET              1060
#define IDC_GRAMLINKQUERY               1061
#define IDC_GRAMLISTQUERY               1062
#define IDC_EDIT1                       1062
#define IDC_GRAMBEFOREEDIT              1062
#define IDC_BOOKMARKEDIT                1062
#define IDC_GRAMPATH                    1062
#define IDC_CORRPHRASE                  1062
#define IDC_BESTPATHTXT                 1062
#define IDC_CORRNAME                    1062
#define IDC_RESSPLITEDIT                1062
#define IDC_GRAMADDCUSTEDIT             1062
#define IDC_GRAPHOUTPUT                 1062
#define IDC_TRAINTEXT                   1062
#define IDC_EDIT2                       1063
#define IDC_GRAMAFTEREDIT               1063
#define IDC_GRAMLINKNAME                1063
#define IDC_GRAMDICTAPPLY               1064
#define IDC_GRAMLISTNAME                1064
#define IDC_GRAMDICTHINT                1065
#define IDC_GRAMAPPENDEDIT              1065
#define IDC_GRAMDICTWORDS               1066
#define IDC_GRAMACTIVATE                1067
#define IDC_SELPROPENG                  1071
#define IDC_SELPROPGRAM                 1072
#define IDC_NOTIFYATTR                  1072
#define IDC_NOTIFYINTERFER              1073
#define IDC_SELPROPRES                  1073
#define IDC_NOTIFYSND                   1074
#define IDC_NOTIFYUTTR                  1075
#define IDC_NOTIFYVMETER                1076
#define IDC_NOTIFYOUTPUT                1077
#define IDC_GRAMNOTBOOKMARK             1078
#define IDC_GRAMNOTPAUSED               1079
#define IDC_GRAMNOTPHRASE               1080
#define IDC_GRAMNOTPHRASHYP             1081
#define IDC_GRAMNOTREEVAL               1082
#define IDC_GRAMNOTUNARC                1083
#define IDC_GRAMNOTOUTPUT               1084
#define IDC_ISRDLGABOUT                 1086
#define IDC_ISRDLGLEX                   1087
#define IDC_ISRDLGTRAINMIC              1088
#define IDC_ISRDLGTRAINGEN              1089
#define IDC_ENGCTLPAUSE                 1089
#define IDC_ISRDLGGENERAL               1090
#define IDC_TRAINPHRASE                 1091
#define IDC_POSGETOUTPUT                1093
#define IDC_POSITIONTRACK               1094
#define IDC_ABOUT                       1095
#define IDC_TOFILEOUTPUT                1095
#define IDC_GRAMDETERIORGET             1099
#define IDC_GRAMBOOKMARK                1100
#define IDC_GRAMDETERIORSET             1101
#define IDC_GRAMDETERIOROUT             1103
#define IDC_CENTMODEGET                 1107
#define IDC_LIKELYWORDS                 1108
#define IDC_GRAMBROWSE                  1109
#define IDC_LISTSEQUENCE                1110
#define IDC_GRAMMARS                    1112
#define IDC_FEATURES                    1113
#define IDC_CFGORIGLIST                 1115
#define IDC_DLGTITLEOPT                 1116
#define IDC_GRAMRESCAN                  1117
#define IDC_UNICODETYPE                 1121
#define IDC_USESHARE                    1124
#define IDC_DEVICEID                    1126
#define IDC_DEVICEIDTXT                 1127
#define IDC_RESOBJSELECT                1129
#define IDC_RESIDENTIFY                 1130
#define IDC_IDENTIFYTXT                 1131
#define IDC_RESTIMEGET                  1132
#define IDC_TIMEBEGINTXT                1133
#define IDC_AUDIOGETWAVE                1133
#define IDC_TIMEENDTXT                  1134
#define IDC_AUDIOFMTTXT                 1134
#define IDC_CORRCONF                    1135
#define IDC_FLAGSGETTXT                 1135
#define IDC_CORRCORR                    1136
#define IDC_PHRASEGETTXT                1136
#define IDC_CORRVALIDATE                1137
#define IDC_CORRVALID                   1138
#define IDC_FLAGSGET                    1139
#define IDC_PHRASEGET                   1140
#define IDC_BESTPATHPH                  1141
#define IDC_BESTPATHW                   1142
#define IDC_PATHSCOREPH                 1143
#define IDC_PATHSCOREW                  1144
#define IDC_SCOREPHTXT                  1145
#define IDC_SCOREWTXT                   1146
#define IDC_MODGUIHIDE                  1146
#define IDC_GETPHNODE                   1147
#define IDC_MODGUIMOVE                  1147
#define IDC_GETWNODE                    1148
#define IDC_MODGUISHOW                  1148
#define IDC_SPKRCORR                    1149
#define IDC_GETPHNODETXT                1149
#define IDC_SPKRCONF                    1150
#define IDC_GETWORDNODETXT              1150
#define IDC_SPKRVALIDATE                1151
#define IDC_IDFORFREE                   1152
#define IDC_SPKRIDENTIFY                1153
#define IDC_IDFORFREETXT                1154
#define IDC_SPKRIDTXT                   1155
#define IDC_MEMGET                      1155
#define IDC_SPKRCORRCONF                1156
#define IDC_LOCKGET                     1156
#define IDC_LOCKSET                     1157
#define IDC_LOCKSETSEL                  1158
#define IDC_LOCKGETTXT                  1159
#define IDC_MEMGETTXT                   1160
#define IDC_MEMFREE                     1161
#define IDC_MEMFREELST                  1162
#define IDC_REEVALUATE                  1163
#define IDC_REEVALTXT                   1164
#define IDC_RESMERGE                    1165
#define IDC_RESSPLIT                    1166
#define IDC_RESMERGESEL                 1167
#define IDC_RESSPLITTXT                 1168
#define IDC_RESMERGETXT                 1169
#define IDC_GRAMCUSTOM                  1169
#define IDC_GRAMRULE                    1171
#define IDC_GRAMPAUSE                   1172
#define IDC_GRAMWND                     1173
#define IDC_GRAMACTIVATEBUT             1174
#define IDC_GRAMDEACTIVATEGRAM          1175
#define IDC_RULEACTIVELIST              1176
#define IDC_USEARCHIVE                  1177
#define IDC_SRRESAUDIO                  1180
#define IDC_SRRESCORRECTION             1181
#define IDC_SRRESEVAL                   1183
#define IDC_SRRESPHONEMEGRAPH           1184
#define IDC_SRRESWORDGRAPH              1185
#define IDC_SRRESLOCKED                 1186
#define IDC_PHRASECONFIDENCE            1187
#define IDC_WORDCONFIDENCES             1188
#define IDC_GETPHRASESCORE              1189
#define IDC_GETWORDSCORES               1190
#define IDC_WORDSCORETEXT               1191
#define IDC_PHRASESCORETEXT             1192
#define IDS_PROPCAPTION                 59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1193
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
