Attribute VB_Name = "VBSPEECH"
Public Const SVFN_LEN = (262)
Public Const LANG_LEN = (64)
Public Const EI_TITLESIZE = (128)
Public Const EI_DESCSIZE = (512)
Public Const EI_FIXSIZE = (512)
Public Const SVPI_MFGLEN = (64)
Public Const SVPI_PRODLEN = (64)
Public Const SVPI_COMPLEN = (64)
Public Const SVPI_COPYRIGHTLEN = (128)
Public Const SVI_MFGLEN = (SVPI_MFGLEN)

Public Const AUDERR_NONE = &H0
Public Const AUDERR_BADDEVICEID = &H80040301
Public Const AUDERR_NEEDWAVEFORMAT = &H80040302
Public Const AUDERR_NOTSUPPORTED = &H80004001
Public Const AUDERR_NOTENOUGHDATA = &H80040201
Public Const AUDERR_NOTPLAYING = &H80040306
Public Const AUDERR_INVALIDPARAM = &H80070057
Public Const AUDERR_WAVEFORMATNOTSUPPORTED = &H80040202
Public Const AUDERR_WAVEDEVICEBUSY = &H80040203
Public Const AUDERR_WAVEDEVNOTSUPPORTED = &H80040312
Public Const AUDERR_NOTRECORDING = &H80040313
Public Const AUDERR_INVALIDFLAG = &H80040204
Public Const AUDERR_INVALIDHANDLE = &H80070006
Public Const AUDERR_NODRIVER = &H80040317
Public Const AUDERR_HANDLEBUSY = &H80040318
Public Const AUDERR_INVALIDNOTIFYSINK = &H80040319
Public Const AUDERR_WAVENOTENABLED = &H8004031A
Public Const AUDERR_ALREADYCLAIMED = &H8004031D
Public Const AUDERR_NOTCLAIMED = &H8004031E
Public Const AUDERR_STILLPLAYING = &H8004031F
Public Const AUDERR_ALREADYSTARTED = &H80040320
Public Const AUDERR_SYNCNOTALLOWED = &H80040321
 
Public Const SRERR_NONE = &H0
Public Const SRERR_OUTOFDISK = &H80040205
Public Const SRERR_NOTSUPPORTED = &H80004001
Public Const SRERR_NOTENOUGHDATA = &H80040201
Public Const SRERR_VALUEOUTOFRANGE = &H8000FFFF
Public Const SRERR_GRAMMARTOOCOMPLEX = &H80040406
Public Const SRERR_GRAMMARWRONGTYPE = &H80040407
Public Const SRERR_INVALIDWINDOW = &H8004000F
Public Const SRERR_INVALIDPARAM = &H80070057
Public Const SRERR_INVALIDMODE = &H80040206
Public Const SRERR_TOOMANYGRAMMARS = &H8004040B
Public Const SRERR_INVALIDLIST = &H80040207
Public Const SRERR_WAVEDEVICEBUSY = &H80040203
Public Const SRERR_WAVEFORMATNOTSUPPORTED = &H80040202
Public Const SRERR_INVALIDCHAR = &H80040208
Public Const SRERR_GRAMTOOCOMPLEX = &H80040406
Public Const SRERR_GRAMTOOLARGE = &H80040411
Public Const SRERR_INVALIDINTERFACE = &H80004002
Public Const SRERR_INVALIDKEY = &H80040209
Public Const SRERR_INVALIDFLAG = &H80040204
Public Const SRERR_GRAMMARERROR = &H80040416
Public Const SRERR_INVALIDRULE = &H80040417
Public Const SRERR_RULEALREADYACTIVE = &H80040418
Public Const SRERR_RULENOTACTIVE = &H80040419
Public Const SRERR_NOUSERSELECTED = &H8004041A
Public Const SRERR_BAD_PRONUNCIATION = &H8004041B
Public Const SRERR_DATAFILEERROR = &H8004041C
Public Const SRERR_GRAMMARALREADYACTIVE = &H8004041D
Public Const SRERR_GRAMMARNOTACTIVE = &H4041E
Public Const SRERR_GLOBALGRAMMARALREADYACTIVE = &H8004041F
Public Const SRERR_LANGUAGEMISMATCH = &H80040420
Public Const SRERR_MULTIPLELANG = &H80040421
Public Const SRERR_LDGRAMMARNOWORDS = &H80040422
Public Const SRERR_NOLEXICON = &H80040423
Public Const SRERR_SPEAKEREXISTS = &H80040424
Public Const SRERR_GRAMMARENGINEMISMATCH = &H80040425
Public Const SRERR_BOOKMARKEXISTS = &H80040426
Public Const SRERR_BOOKMARKDOESNOTEXIST = &H80040427
Public Const SRERR_MICWIZARDCANCELED = &H80040428
Public Const SRERR_WORDTOOLONG = &H80040429
Public Const SRERR_BAD_WORD = &H8004042A
Public Const E_WRONGTYPE = &H8004020C
Public Const E_BUFFERTOOSMALL = &H8004020D

Public Const TTSERR_NONE = &H0
Public Const TTSERR_INVALIDINTERFACE = &H80004002
Public Const TTSERR_OUTOFDISK = &H80040205
Public Const TTSERR_NOTSUPPORTED = &H80004001
Public Const TTSERR_VALUEOUTOFRANGE = &H8000FFFF
Public Const TTSERR_INVALIDWINDOW = &H8004000F
Public Const TTSERR_INVALIDPARAM = &H80070057
Public Const TTSERR_INVALIDMODE = &H80040206
Public Const TTSERR_INVALIDKEY = &H80040209
Public Const TTSERR_WAVEFORMATNOTSUPPORTED = &H80040202
Public Const TTSERR_INVALIDCHAR = &H80040208
Public Const TTSERR_QUEUEFULL = &H8004020A
Public Const TTSERR_WAVEDEVICEBUSY = &H80040203
Public Const TTSERR_NOTPAUSED = &H80040501
Public Const TTSERR_ALREADYPAUSED = &H80040502

Public Const VCMDERR_NONE = &H0
Public Const VCMDERR_OUTOFMEM = &H8007000E
Public Const VCMDERR_OUTOFDISK = &H80040205
Public Const VCMDERR_NOTSUPPORTED = &H80004001
Public Const VCMDERR_VALUEOUTOFRANGE = &H8000FFFF
Public Const VCMDERR_MENUTOOCOMPLEX = &H80040606
Public Const VCMDERR_MENUWRONGLANGUAGE = &H80040607
Public Const VCMDERR_INVALIDWINDOW = &H8004000F
Public Const VCMDERR_INVALIDPARAM = &H80070057
Public Const VCMDERR_INVALIDMODE = &H80040206
Public Const VCMDERR_TOOMANYMENUS = &H8004060
Public Const VCMDERR_INVALIDLIST = &H80040207
Public Const VCMDERR_MENUDOESNOTEXIST = &H8004060D
Public Const VCMDERR_MENUACTIVE = &H8004060E
Public Const VCMDERR_NOENGINE = &H8004060F
Public Const VCMDERR_NOGRAMMARINTERFACE = &H80040610
Public Const VCMDERR_NOFINDINTERFACE = &H80040611
Public Const VCMDERR_CANTCREATESRENUM = &H80040612
Public Const VCMDERR_NOSITEINFO = &H80040613
Public Const VCMDERR_SRFINDFAILED = &H80040614
Public Const VCMDERR_CANTCREATEAUDIODEVICE = &H80040615
Public Const VCMDERR_CANTSETDEVICE = &H80040616
Public Const VCMDERR_CANTSELECTENGINE = &H80040617
Public Const VCMDERR_CANTCREATENOTIFY = &H80040618
Public Const VCMDERR_CANTCREATEDATASTRUCTURES = &H80040619
Public Const VCMDERR_CANTINITDATASTRUCTURES = &H8004061A
Public Const VCMDERR_NOCACHEDATA = &H8004061B
Public Const VCMDERR_NOCOMMANDS = &H8004061C
Public Const VCMDERR_CANTXTRACTWORDS = &H8004061D
Public Const VCMDERR_CANTGETDBNAME = &H8004061E
Public Const VCMDERR_CANTCREATEKEY = &H8004061F
Public Const VCMDERR_CANTCREATEDBNAME = &H80040620
Public Const VCMDERR_CANTUPDATEREGISTRY = &H80040621
Public Const VCMDERR_CANTOPENREGISTRY = &H80040622
Public Const VCMDERR_CANTOPENDATABASE = &H80040623
Public Const VCMDERR_CANTCREATESTORAGE = &H80040624
Public Const VCMDERR_CANNOTMIMIC = &H80040625
Public Const VCMDERR_MENUEXIST = &H80040626
Public Const VCMDERR_MENUOPEN = &H80040627
Public Const VTXTERR_NONE = &H0
Public Const VTXTERR_OUTOFMEM = &H8007000E
Public Const VTXTERR_EMPTYSPEAKSTRING = &H8004020B
Public Const VTXTERR_INVALIDPARAM = &H80070057
Public Const VTXTERR_INVALIDMODE = &H80040206
Public Const VTXTERR_NOENGINE = &H8004070F
Public Const VTXTERR_NOFINDINTERFACE = &H80040711
Public Const VTXTERR_CANTCREATETTSENUM = &H80040712
Public Const VTXTERR_NOSITEINFO = &H80040713
Public Const VTXTERR_TTSFINDFAILED = &H80040714
Public Const VTXTERR_CANTCREATEAUDIODEVICE = &H80040715
Public Const VTXTERR_CANTSETDEVICE = &H80040716
Public Const VTXTERR_CANTSELECTENGINE = &H80040717
Public Const VTXTERR_CANTCREATENOTIFY = &H80040718
Public Const VTXTERR_NOTENABLED = &H80040719
Public Const VTXTERR_OUTOFDISK = &H80040205
Public Const VTXTERR_NOTSUPPORTED = &H80004001
Public Const VTXTERR_NOTENOUGHDATA = &H80040201
Public Const VTXTERR_QUEUEFULL = &H8004020A
Public Const VTXTERR_VALUEOUTOFRANGE = &H8000FFFF
Public Const VTXTERR_INVALIDWINDOW = &H8004000F
Public Const VTXTERR_WAVEDEVICEBUSY = &H80040203
Public Const VTXTERR_WAVEFORMATNOTSUPPORTED = &H80040202
Public Const VTXTERR_INVALIDCHAR = &H80040208
Public Const LEXERR_INVALIDTEXTCHAR = &H80040801
Public Const LEXERR_INVALIDSENSE = &H80040802
Public Const LEXERR_NOTINLEX = &H80040803
Public Const LEXERR_OUTOFDISK = &H80040804
Public Const LEXERR_INVALIDPRONCHAR = &H80040805
Public Const LEXERR_ALREADYINLEX = &H40806
Public Const LEXERR_PRNBUFTOOSMALL = &H80040807
Public Const LEXERR_ENGBUFTOOSMALL = &H80040808
Public Const LEXERR_INVALIDLEX = &H80040809

Public Const CHARSET_TEXT = 0
Public Const CHARSET_IPAPHONETIC = 1
Public Const CHARSET_ENGINEPHONETIC = 2
Public Const VPS_UNKNOWN = 0
Public Const VPS_NOUN = 1
Public Const VPS_VERB = 2
Public Const VPS_ADVERB = 3
Public Const VPS_ADJECTIVE = 4
Public Const VPS_PROPERNOUN = 5
Public Const VPS_PRONOUN = 6
Public Const VPS_CONJUNCTION = 7
Public Const VPS_CARDINAL = 8
Public Const VPS_ORDINAL = 9
Public Const VPS_DETERMINER = 10
Public Const VPS_QUANTIFIER = 11
Public Const VPS_PUNCTUATION = 12
Public Const VPS_CONTRACTION = 13
Public Const VPS_INTERJECTION = 14
Public Const VPS_ABBREVIATION = 15
Public Const VPS_PREPOSITION = 16

Public Const TTSBASEATTR = &H1000
Public Const SRBASEATTR = &H2000
Public Const VDCTBASEATTR = &H3000
Public Const VCMDBASEATTR = &H4000
Public Const VTXTBASEATTR = &H5000
Public Const AUDBASEATTR = &H6000
Public Const TTSATTR_PITCH = (1)
Public Const TTSATTR_REALTIME = (0)
Public Const TTSATTR_SPEED = (2)
Public Const TTSATTR_VOLUME = (3)
Public Const TTSATTR_PITCHRANGE = (TTSBASEATTR + 5)
Public Const TTSATTR_PITCHRANGEDEFAULT = (TTSBASEATTR + 6)
Public Const TTSATTR_PITCHRANGEMAX = (TTSBASEATTR + 7)
Public Const TTSATTR_PITCHRANGEMIN = (TTSBASEATTR + 8)
Public Const TTSATTR_PITCHRANGERELATIVE = (TTSBASEATTR + 9)
Public Const TTSATTR_PITCHRANGERELATIVEMAX = (TTSBASEATTR + 10)
Public Const TTSATTR_PITCHRANGERELATIVEMIN = (TTSBASEATTR + 11)
Public Const TTSATTR_PITCHRELATIVE = (TTSBASEATTR + 12)
Public Const TTSATTR_PITCHRELATIVEMAX = (TTSBASEATTR + 13)
Public Const TTSATTR_PITCHRELATIVEMIN = (TTSBASEATTR + 14)
Public Const TTSATTR_PITCHDEFAULT = (TTSBASEATTR + 15)
Public Const TTSATTR_PITCHMAX = (TTSBASEATTR + 16)
Public Const TTSATTR_PITCHMIN = (TTSBASEATTR + 17)
Public Const TTSATTR_SPEEDRELATIVE = (TTSBASEATTR + 18)
Public Const TTSATTR_SPEEDRELATIVEMAX = (TTSBASEATTR + 19)
Public Const TTSATTR_SPEEDRELATIVEMIN = (TTSBASEATTR + 20)
Public Const TTSATTR_SPEEDDEFAULT = (TTSBASEATTR + 21)
Public Const TTSATTR_SPEEDMAX = (TTSBASEATTR + 22)
Public Const TTSATTR_SPEEDMIN = (TTSBASEATTR + 23)
Public Const TTSATTR_THREADPRIORITY = (TTSBASEATTR + 24)
Public Const TTSATTR_SINKFLAGS = (TTSBASEATTR + 25)
Public Const TTSATTR_VOLUMEDEFAULT = (TTSBASEATTR + 26)

Public Const SRATTR_AUTOGAIN = (1)
Public Const SRATTR_ECHO = (3)
Public Const SRATTR_ENERGYFLOOR = (4)
Public Const SRATTR_MICROPHONE = (5)
Public Const SRATTR_REALTIME = (6)
Public Const SRATTR_SPEAKER = (7)
Public Const SRATTR_TIMEOUT_COMPLETE = (8)
Public Const SRATTR_TIMEOUT_INCOMPLETE = (SRBASEATTR + 8)
Public Const SRATTR_THRESHOLD = (2)
Public Const SRATTR_ACCURACYSLIDER = (SRBASEATTR + 10)
Public Const SRATTR_LEVEL = (SRBASEATTR + 11)
Public Const SRATTR_LISTENINGSTATE = (SRBASEATTR + 12)
Public Const SRATTR_RESULTSINFO = (SRBASEATTR + 13)
Public Const SRATTR_RESULTSINFO_POSSIBLE = (SRBASEATTR + 14)
Public Const SRATTR_SINKFLAGS = (SRBASEATTR + 15)
Public Const SRATTR_THREADPRIORITY = (SRBASEATTR + 16)

Public Const VDCTATTR_AWAKESTATE = (VDCTBASEATTR + 1)
Public Const VDCTATTR_MODE = (VDCTBASEATTR + 2)
Public Const VDCTATTR_MEMORY = (VDCTBASEATTR + 3)
Public Const VDCTATTR_CORRECTIONRECT = (VDCTBASEATTR + 4)

Public Const VCMDATTR_AWAKESTATE = (VCMDBASEATTR + 1)
Public Const VCMDATTR_DEVICE = (VCMDBASEATTR + 2)
Public Const VCMDATTR_ENABLED = (VCMDBASEATTR + 3)
Public Const VCMDATTR_SRMODE = (VCMDBASEATTR + 4)

Public Const AUDATTR_USELOWPRIORITY = (AUDBASEATTR + 1)
Public Const AUDATTR_AUTORETRY = (AUDBASEATTR + 2)

Public Const SRRI_AUDIO = 1
Public Const SRRI_AUDIO_UNCOMPRESSED = 2
Public Const SRRI_ALTERNATIVES = 4
Public Const SRRI_WORDGRAPH = 8
Public Const SRRI_PHONEMEGRAPH = 16

Public Const SRASF_ATTRIBUTES = 1
Public Const SRASF_INTERFERENCE = 2
Public Const SRASF_SOUND = 4
Public Const SRASF_UTTERANCEBEGIN = 8
Public Const SRASF_UTTERANCEEND = 16
Public Const SRASF_VUMETER = 32
Public Const SRASF_PHRASEHYPOTHESIS = 64
Public Const SRASF_TRAINING = 128
Public Const SRASF_ERRORWARNING = 256

Public Const ILP2_ACTIVE = 1
Public Const ILP2_USER = 2
Public Const ILP2_BACKUP = 4
Public Const ILP2_LTS = 8

Public Const STMWU_CNC = 0
Public Const STMWU_DICTATION = 1
Public Const STMWU_LOWERGAIN = &H10000
Public Const STMWU_NOAUTOGAIN = &H20000

Public Const STMWF_CANSKIP = 1

Public Const STMWI_UNKNOWN = 0
Public Const STMWI_CLOSETALK = 1
Public Const STMWI_EARPIECE = 2
Public Const STMWI_HANDSET = 3
Public Const STMWI_CLIPON = 4
Public Const STMWI_DESKTOP = 5
Public Const STMWI_HANDHELD = 6
Public Const STMWI_TOPMONITOR = 7
Public Const STMWI_INMONITOR = 8
Public Const STMWI_KEYBOARD = 9
Public Const STMWI_REMOTE = 10

Public Const STMWIS_UNKNOWN = 0
Public Const STMWIS_SPEAKERS = 1
Public Const STMWIS_HEADPHONES = 2
Public Const STMWIS_BOTH = 3

Public Const STLD_DISABLEREMOVE = 1
Public Const STLD_DISABLEADD = 2
Public Const STLD_FORCEEDIT = 4
Public Const STLD_DISABLEPRONADDREMOVE = 8
Public Const STLD_TEST = 16
Public Const STLD_DISABLERENAME = 32
Public Const STLD_CHANGEPRONADDS = 64
Public Const IANSRSN_NODATA = 0
Public Const IANSRSN_PRIORITY = 1
Public Const IANSRSN_INACTIVE = 2
Public Const IANSRSN_EOF = 3

Public Const IASISTATE_PASSTHROUGH = 0
Public Const IASISTATE_PASSNOTHING = 1
Public Const IASISTATE_PASSREADFROMWAVE = 2
Public Const IASISTATE_PASSWRITETOWAVE = 3

Public Const SRMI_NAMELEN = SVFN_LEN

Public Const SRSEQUENCE_DISCRETE = (0)
Public Const SRSEQUENCE_CONTINUOUS = (1)
Public Const SRSEQUENCE_WORDSPOT = (2)
Public Const SRSEQUENCE_CONTCFGDISCDICT = (3)

Public Const SRGRAM_CFG = 1
Public Const SRGRAM_DICTATION = 2
Public Const SRGRAM_LIMITEDDOMAIN = 4

Public Const SRFEATURE_INDEPSPEAKER = 1
Public Const SRFEATURE_INDEPMICROPHONE = 2
Public Const SRFEATURE_TRAINWORD = 4
Public Const SRFEATURE_TRAINPHONETIC = 8
Public Const SRFEATURE_WILDCARD = 16
Public Const SRFEATURE_ANYWORD = 32
Public Const SRFEATURE_PCOPTIMIZED = 64
Public Const SRFEATURE_PHONEOPTIMIZED = 128
Public Const SRFEATURE_GRAMLIST = 256
Public Const SRFEATURE_GRAMLINK = 512
Public Const SRFEATURE_MULTILINGUAL = 1024
Public Const SRFEATURE_GRAMRECURSIVE = 2048
Public Const SRFEATURE_IPAUNICODE = 4096
Public Const SRFEATURE_SINGLEINSTANCE = 8192
Public Const SRFEATURE_THREADSAFE = 16384
Public Const SRFEATURE_FIXEDAUDIO = 32768
Public Const SRFEATURE_IPAWORD = 65536
Public Const SRFEATURE_SAPI4 = 131072

Public Const SRI_ILEXPRONOUNCE = 1
Public Const SRI_ISRATTRIBUTES = 2
Public Const SRI_ISRCENTRAL = 4
Public Const SRI_ISRDIALOGS = 8
Public Const SRI_ISRGRAMCOMMON = 16
Public Const SRI_ISRGRAMCFG = 32
Public Const SRI_ISRGRAMDICTATION = 64
Public Const SRI_ISRGRAMINSERTIONGUI = 128
Public Const SRI_ISRESBASIC = 256
Public Const SRI_ISRESMERGE = 512
Public Const SRI_ISRESAUDIO = 1024
Public Const SRI_ISRESCORRECTION = 2048
Public Const SRI_ISRESEVAL = 4096
Public Const SRI_ISRESGRAPH = 8192
Public Const SRI_ISRESMEMORY = 16384
Public Const SRI_ISRESMODIFYGUI = 32768
Public Const SRI_ISRESSPEAKER = 65536
Public Const SRI_ISRSPEAKER = 131072
Public Const SRI_ISRESSCORES = 262144
Public Const SRI_ISRESAUDIOEX = 524288
Public Const SRI_ISRGRAMLEXPRON = 1048576
Public Const SRI_ISRRESGRAPHEX = 2097152
Public Const SRI_ILEXPRONOUNCE2 = 4194304
Public Const SRI_IATTRIBUTES = 8388608

Public Const SRGRAMQ_NONE = 0
Public Const SRGRAMQ_GENERALTRAIN = 1
Public Const SRGRAMQ_PHRASE = 2
Public Const SRGRAMQ_DIALOG = 3

Public Const ISRNOTEFIN_RECOGNIZED = 1
Public Const ISRNOTEFIN_THISGRAMMAR = 2
Public Const ISRNOTEFIN_FROMTHISGRAMMAR = 4

Public Const SRGNSTRAIN_GENERAL = 1
Public Const SRGNSTRAIN_GRAMMAR = 2
Public Const SRGNSTRAIN_MICROPHONE = 4

Public Const ISRNSAC_AUTOGAINENABLE = 1
Public Const ISRNSAC_THRESHOLD = 2
Public Const ISRNSAC_ECHO = 3
Public Const ISRNSAC_ENERGYFLOOR = 4
Public Const ISRNSAC_MICROPHONE = 5
Public Const ISRNSAC_REALTIME = 6
Public Const ISRNSAC_SPEAKER = 7
Public Const ISRNSAC_TIMEOUT = 8
Public Const ISRNSAC_STARTLISTENING = 9
Public Const ISRNSAC_STOPLISTENING = 10

Public Const SRMSGINT_NOISE = (&H1)
Public Const SRMSGINT_NOSIGNAL = (&H2)
Public Const SRMSGINT_TOOLOUD = (&H3)
Public Const SRMSGINT_TOOQUIET = (&H4)
Public Const SRMSGINT_AUDIODATA_STOPPED = (&H5)
Public Const SRMSGINT_AUDIODATA_STARTED = (&H6)
Public Const SRMSGINT_IAUDIO_STARTED = (&H7)
Public Const SRMSGINT_IAUDIO_STOPPED = (&H8)

Public Const SRHDRTYPE_CFG = 0
Public Const SRHDRTYPE_LIMITEDDOMAIN = 1
Public Const SRHDRTYPE_DICTATION = 2

Public Const SRHDRFLAG_UNICODE = 1

Public Const SRRESCUE_COMMA = 1
Public Const SRRESCUE_DECLARATIVEBEGIN = 2
Public Const SRRESCUE_DECLARATIVEEND = 3
Public Const SRRESCUE_IMPERATIVEBEGIN = 4
Public Const SRRESCUE_IMPERATIVEEND = 5
Public Const SRRESCUE_INTERROGATIVEBEGIN = 6
Public Const SRRESCUE_INTERROGATIVEEND = 7
Public Const SRRESCUE_NOISE = 8
Public Const SRRESCUE_PAUSE = 9
Public Const SRRESCUE_SENTENCEBEGIN = 10
Public Const SRRESCUE_SENTENCEEND = 11
Public Const SRRESCUE_UM = 12
Public Const SRRESCUE_WILDCARD = 13
Public Const SRRESCUE_WORD = 14

Public Const SRCFG_STARTOPERATION = (1)
Public Const SRCFG_ENDOPERATION = (2)
Public Const SRCFG_WORD = (3)
Public Const SRCFG_RULE = (4)
Public Const SRCFG_WILDCARD = (5)
Public Const SRCFG_LIST = (6)

Public Const SRCFGO_SEQUENCE = (1)
Public Const SRCFGO_ALTERNATIVE = (2)
Public Const SRCFGO_REPEAT = (3)
Public Const SRCFGO_OPTIONAL = (4)

Public Const SRCK_LANGUAGE = 1
Public Const SRCKCFG_WORDS = 2
Public Const SRCKCFG_RULES = 3
Public Const SRCKCFG_EXPORTRULES = 4
Public Const SRCKCFG_IMPORTRULES = 5
Public Const SRCKCFG_LISTS = 6
Public Const SRCKD_TOPIC = 7
Public Const SRCKD_COMMON = 8
Public Const SRCKD_GROUP = 9
Public Const SRCKD_SAMPLE = 10
Public Const SRCKLD_WORDS = 11
Public Const SRCKLD_GROUP = 12
Public Const SRCKLD_SAMPLE = 13
Public Const SRCKD_WORDCOUNT = 14
Public Const SRCKD_NGRAM = 15

Public Const SRTQEX_REQUIRED = (&H0)
Public Const SRTQEX_RECOMMENDED = (&H1)

Public Const SRAUDIOTIMESTAMP_DEFAULT = -1

Public Const SRCORCONFIDENCE_SOME = 1
Public Const SRCORCONFIDENCE_VERY = 2

Public Const SRGEX_ACOUSTICONLY = 1
Public Const SRGEX_LMONLY = 2
Public Const SRGEX_ACOUSTICANDLM = 4

Public Const SRRESMEMKIND_AUDIO = 1
Public Const SRRESMEMKIND_CORRECTION = 2
Public Const SRRESMEMKIND_EVAL = 4
Public Const SRRESMEMKIND_PHONEMEGRAPH = 8
Public Const SRRESMEMKIND_WORDGRAPH = 16

Public Const SRATTR_MINAUTOGAIN = 0
Public Const SRATTR_MAXAUTOGAIN = 100
Public Const SRATTR_MINENERGYFLOOR = 0
Public Const SRATTR_MAXENERGYFLOOR = &HFFFF
Public Const SRATTR_MINREALTIME = 0
Public Const SRATTR_MAXREALTIME = &HFFFFFFFF
Public Const SRATTR_MINTHRESHOLD = 0
Public Const SRATTR_MAXTHRESHOLD = 100
Public Const SRATTR_MINTOINCOMPLETE = 0
Public Const SRATTR_MAXTOINCOMPLETE = &HFFFFFFFF
Public Const SRATTR_MINTOCOMPLETE = 0
Public Const SRATTR_MAXTOCOMPLETE = &HFFFFFFFF

Public Const SRGRMFMT_CFG = &H0
Public Const SRGRMFMT_LIMITEDDOMAIN = &H1

Public Const SRGRMFMT_DICTATION = &H2

Public Const SRGRMFMT_CFGNATIVE = &H8000

Public Const SRGRMFMT_LIMITEDDOMAINNATIVE = &H8001

Public Const SRGRMFMT_DICTATIONNATIVE = &H8002

Public Const TTSI_NAMELEN = SVFN_LEN
Public Const TTSI_STYLELEN = SVFN_LEN

Public Const GENDER_NEUTRAL = (0)
Public Const GENDER_FEMALE = (1)
Public Const GENDER_MALE = (2)

Public Const TTSFEATURE_ANYWORD = 1
Public Const TTSFEATURE_VOLUME = 2
Public Const TTSFEATURE_SPEED = 4
Public Const TTSFEATURE_PITCH = 8
Public Const TTSFEATURE_TAGGED = 16
Public Const TTSFEATURE_IPAUNICODE = 32
Public Const TTSFEATURE_VISUAL = 64
Public Const TTSFEATURE_WORDPOSITION = 128
Public Const TTSFEATURE_PCOPTIMIZED = 256
Public Const TTSFEATURE_PHONEOPTIMIZED = 512
Public Const TTSFEATURE_FIXEDAUDIO = 1024
Public Const TTSFEATURE_SINGLEINSTANCE = 2048
Public Const TTSFEATURE_THREADSAFE = 4096
Public Const TTSFEATURE_IPATEXTDATA = 8192
Public Const TTSFEATURE_PREFERRED = 16384
Public Const TTSFEATURE_TRANSPLANTED = 32768
Public Const TTSFEATURE_SAPI4 = 65536

Public Const TTSI_ILEXPRONOUNCE = 1
Public Const TTSI_ITTSATTRIBUTES = 2
Public Const TTSI_ITTSCENTRAL = 4
Public Const TTSI_ITTSDIALOGS = 8
Public Const TTSI_ATTRIBUTES = 16

Public Const TTSDATAFLAG_TAGGED = 1

Public Const TTSBNS_ABORTED = 1

Public Const TTSNSAC_REALTIME = 0
Public Const TTSNSAC_PITCH = 1
Public Const TTSNSAC_SPEED = 2
Public Const TTSNSAC_VOLUME = 3


Public Const TTSNSHINT_QUESTION = 1
Public Const TTSNSHINT_STATEMENT = 2
Public Const TTSNSHINT_COMMAND = 4
Public Const TTSNSHINT_EXCLAMATION = 8
Public Const TTSNSHINT_EMPHASIS = 16

Public Const TTSAGE_BABY = 1
Public Const TTSAGE_TODDLER = 3
Public Const TTSAGE_CHILD = 6
Public Const TTSAGE_ADOLESCENT = 14
Public Const TTSAGE_ADULT = 30
Public Const TTSAGE_ELDERLY = 70

Public Const TTSATTR_MINPITCH = 0
Public Const TTSATTR_MAXPITCH = &HFFFF
Public Const TTSATTR_MINREALTIME = 0
Public Const TTSATTR_MAXREALTIME = &HFFFFFFFF
Public Const TTSATTR_MINSPEED = 0
Public Const TTSATTR_MAXSPEED = &HFFFFFFFF
Public Const TTSATTR_MINVOLUME = 0
Public Const TTSATTR_MAXVOLUME = &HFFFFFFFF

Public Const VCMD_APPLEN = 32
Public Const VCMD_STATELEN = VCMD_APPLEN
Public Const VCMD_MICLEN = VCMD_APPLEN
Public Const VCMD_SPEAKERLEN = VCMD_APPLEN

Public Const VCMDMC_CREATE_TEMP = &H1
Public Const VCMDMC_CREATE_NEW = &H2
Public Const VCMDMC_CREATE_ALWAYS = &H4
Public Const VCMDMC_OPEN_ALWAYS = &H8
Public Const VCMDMC_OPEN_EXISTING = &H10

Public Const VCMDRF_NOMESSAGES = &H0
Public Const VCMDRF_ALLBUTVUMETER = &H1
Public Const VCMDRF_VUMETER = &H2
Public Const VCMDRF_ALLMESSAGES = (VCMDRF_ALLBUTVUMETER + VCMDRF_VUMETER)

Public Const VCMDEF_DATABASE = &H0
Public Const VCMDEF_ACTIVE = &H1
Public Const VCMDEF_SELECTED = &H2
Public Const VCMDEF_PERMANENT = &H4
Public Const VCMDEF_TEMPORARY = &H8

Public Const VWGFLAG_ASLEEP = &H1

Public Const VCMDACT_NORMAL = (&H8000)
Public Const VCMDACT_LOW = (&H4000)
Public Const VCMDACT_HIGH = (&HC000)

Public Const VCMDCMD_VERIFY = &H1
Public Const VCMDCMD_DISABLED_TEMP = &H2
Public Const VCMDCMD_DISABLED_PERM = &H4
Public Const VCMDCMD_CANTRENAME = &H8

Public Const VCMD_BY_POSITION = &H1
Public Const VCMD_BY_IDENTIFIER = &H2

Public Const IVCNSAC_AUTOGAINENABLE = &H1
Public Const IVCNSAC_ENABLED = &H2
Public Const IVCNSAC_AWAKE = &H4
Public Const IVCNSAC_DEVICE = &H8
Public Const IVCNSAC_MICROPHONE = &H10
Public Const IVCNSAC_SPEAKER = &H20
Public Const IVCNSAC_SRMODE = &H40
Public Const IVCNSAC_THRESHOLD = &H80
Public Const IVCNSAC_ORIGINAPP = &H10000

Public Const IVTNSAC_DEVICE = &H1
Public Const IVTNSAC_ENABLED = &H2
Public Const IVTNSAC_SPEED = &H4
Public Const IVTNSAC_VOLUME = &H8
Public Const IVTNSAC_TTSMODE = &H10

Public Const VSRMODE_OFF = &H2
Public Const VSRMODE_DISABLED = &H1
Public Const VSRMODE_CMDPAUSED = &H4
Public Const VSRMODE_CMDONLY = &H10
Public Const VSRMODE_DCTONLY = &H20
Public Const VSRMODE_CMDANDDCT = &H40

Public Const VDCT_TOPICNAMELEN = 32


Public Const VDCT_TEXTADDED = &H1
Public Const VDCT_TEXTREMOVED = &H2
Public Const VDCT_TEXTREPLACED = &H4

Public Const VDCT_TEXTCLEAN = &H10000
Public Const VDCT_TEXTKEEPRESULTS = &H20000

Public Const VDCTGUIF_VISIBLE = &H1
Public Const VDCTGUIF_DONTMOVE = &H2
Public Const VDCTGUIF_ADDWORD = &H4

Public Const VDCTFX_CAPFIRST = &H1
Public Const VDCTFX_LOWERFIRST = &H2
Public Const VDCTFX_TOGGLEFIRST = &H3
Public Const VDCTFX_CAPALL = &H4
Public Const VDCTFX_LOWERALL = &H5
Public Const VDCTFX_REMOVESPACES = &H6
Public Const VDCTFX_KEEPONLYFIRSTLETTER = &H7
Public Const VTXTST_STATEMENT = &H1
Public Const VTXTST_QUESTION = &H2
Public Const VTXTST_COMMAND = &H4
Public Const VTXTST_WARNING = &H8
Public Const VTXTST_READING = &H10
Public Const VTXTST_NUMBERS = &H20
Public Const VTXTST_SPREADSHEET = &H40

Public Const VTXTSP_VERYHIGH = &H80
Public Const VTXTSP_HIGH = &H100
Public Const VTXTSP_NORMAL = &H200

Public Const TTS_LANGUAGE = 1
Public Const TTS_VOICE = 2
Public Const TTS_GENDER = 4
Public Const TTS_VOLUME = 8
Public Const TTS_PITCH = 16
Public Const TTS_SPEED = 32
Public Const TTS_ABBREVIATION = 64
Public Const TTS_PUNCTUATION = 128
Public Const TTS_PAUSEWORD = 256
Public Const TTS_PAUSEPHRASE = 512
Public Const TTS_PAUSESENTENCE = 1024
Public Const TTS_SPELLING = 2048
Public Const TTS_QUALITY = 4096
Public Const TTS_FRICATION = 8192
Public Const TTS_ASPIRATION = 16384
Public Const TTS_INTONATION = 32768

Public Const TTSATTR_MINPAUSEWORD = &H0
Public Const TTSATTR_MAXPAUSEWORD = &HFFFFFFFF
Public Const TTSATTR_MINPAUSEPHRASE = &H0
Public Const TTSATTR_MAXPAUSEPHRASE = &HFFFFFFFF
Public Const TTSATTR_MINPAUSESENTENCE = &H0
Public Const TTSATTR_MAXPAUSESENTENCE = &HFFFFFFFF
Public Const TTSATTR_MINASPIRATION = &H0
Public Const TTSATTR_MAXASPIRATION = &HFFFFFFFF
Public Const TTSATTR_MINFRICATION = &H0
Public Const TTSATTR_MAXFRICATION = &HFFFFFFFF
Public Const TTSATTR_MININTONATION = &H0
Public Const TTSATTR_MAXINTONATION = &HFFFFFFFF

Public Const TTSNSAC_LANGUAGE = 100
Public Const TTSNSAC_VOICE = 101
Public Const TTSNSAC_GENDER = 102
Public Const TTSNSAC_ABBREVIATION = 103
Public Const TTSNSAC_PUNCTUATION = 104
Public Const TTSNSAC_PAUSEWORD = 105
Public Const TTSNSAC_PAUSEPHRASE = 106
Public Const TTSNSAC_PAUSESENTENCE = 107
Public Const TTSNSAC_SPELLING = 108
Public Const TTSNSAC_QUALITY = 109
Public Const TTSNSAC_FRICATION = 110
Public Const TTSNSAC_ASPIRATION = 111
Public Const TTSNSAC_INTONATION = 112
Public Const TTSI_ITTSEXTERNALSYNTHESIZER = 16
Public Const TTSERR_SYNTHESIZERBUSY = &H80004100
Public Const TTSERR_ALREADYDISPLAYED = &H80004101
Public Const TTSERR_INVALIDATTRIB = &H80004102
Public Const TTSERR_SYNTHESIZERACCESSERROR = &H80004103
Public Const TTSERR_DRIVERERROR = &H80004104
Public Const TTSERR_UNRECOVERABLEERROR = &H80004105
Public Const TTSERR_DRIVERACCESSERROR = &H80004106
Public Const TTSERR_BUFFERTOOSMALL = &H80004107
Public Const TTSERR_DRIVERNOTFOUND = &H80004108
Public Const TTSERR_CANNOTREGISTER = &H80004109
Public Const TTSERR_LANGUAGENOTSUPPORTED = &H80004110

